#把我的資料庫檔案，存在這個專案裡面的 data 資料夾裡，檔案名字叫 kitsunedb
spring.datasource.url=jdbc:h2:file:./data/kitsunedb;AUTO_SERVER=TRUE

# H2 資料庫設定（檔案型，資料會存在專案根目錄的 data 資料夾）
spring.datasource.driver-class-name=org.h2.Driver
spring.datasource.username=humankitsune
spring.datasource.password=0000

# 開啟 H2 網頁管理介面 (網址後方加上 /h2-console)
spring.h2.console.enabled=true
spring.h2.console.path=/h2-console

# 讓 Spring Boot 接收 GitHub 雲端的轉發標頭，防止自動跳回 localhost
server.forward-headers-strategy=framework

# JPA 與 Hibernate 設定
#告訴 Spring Boot 如何跟 H2 資料庫 溝通、以及如何自動管理你的資料表格的。
spring.jpa.database-platform=org.hibernate.dialect.H2Dialect
spring.jpa.hibernate.ddl-auto=update

# 允許 H2 Console 使用 Frame（因為 H2 使用了 iframe 技術，這行一定要加）
spring.h2.console.settings.web-allow-others=true
# 確保 Spring Security 不會擋住這個路徑（如果您的專案有用到 security）
spring.security.headers.frame-options.disable=true